= Request Content Limit Policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-request-content-limit/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-request-content-limit/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Scope

|===
|onRequest |onResponse
|X|
|===

== Description

This policy allows to specify a max limit request content lenght allowed on a request.
This limit is compared to the content length header of the request.

== Possible response

|===
|Error |description
|400|Content-length is not a valid integer !
|411|The request did not specify the length of its content, which is required by the requested resource.
|413|The request is larger than the server is willing or able to process.
|===

== Configuration

You can configure the policy with the following options :

|===
|Property |Required |Description |Type

|limit
|true
|The limit of the request content length allowed
|int

|===


[source, json]
.Sample
----
"request-content-limit": {
  "limit": 1000
}
----

== Errors

=== Default error
|===
|Code |Message

.^| ```400```
| The limit from the configuration is not correct.

.^| ```413```
| Incoming HTTP request payload exceed the size limit.

.^| ```411```
| The HTTP request is not chunked and does not specify the `Content-Length` header.

|===

=== Override errors
If you're looking to override the default response provided by the policy, you can do it
thanks to the response templates feature. These templates must be define at the API level (see `Response Templates`
from the `Proxy` menu).

Here are the error keys send by this policy:

[cols="2*", options="header"]
|===
^|Key
^|Parameters

.^|REQUEST_CONTENT_LIMIT_TOO_LARGE
^.^|length - limit

.^|REQUEST_CONTENT_LIMIT_LENGTH_REQUIRED
^.^|limit

|===